function [X, PX] = Kalman_predict_IMU(X, PX, imuACC, imuGYR, Q, dt)
RImu_lidar = [1 0 0; 0 -1 0; 0 0 -1];
u = [RImu_lidar*imuACC'; RImu_lidar*imuGYR'];
X = f(X,u,dt);
PX = Jf_x(X,u,dt)*PX*Jf_x(X,u,dt)' + Jf_u(X,dt)*Q*Jf_u(X,dt)';
end

function pred = f(X,u,dt)
pred = zeros(15,1);
Rx = [1 0 0; 0 cos(X(4)) -sin(X(4)); 0 sin(X(4)) cos(X(4))];
Ry = [cos(X(5)) 0 sin(X(5)); 0 1 0; -sin(X(5)) 0 cos(X(5))];
Rz = [cos(X(6)) -sin(X(6)) 0; sin(X(6)) cos(X(6)) 0; 0 0 1];
Rot = Rz*Ry*Rx;

pred(1:3) = X(1:3) + Rot*((u(1:3)-X(13:15))*dt/2+X(7:9))*dt;
pred(4:6) = X(4:6) + (u(4:6)-X(10:12))*dt;
pred(7:9) = X(7:9) + (u(1:3)-X(13:15))*dt;
pred(10:15) = X(10:15);
end

function jacob = Jf_x(X,u,dt)
jacob = [ 1, 0, 0,  dt*((X(8) - dt*(X(14) - u(2)))*(sin(X(4))*sin(X(6)) + cos(X(4))*cos(X(6))*sin(X(5))) + (X(9) - dt*(X(15) - u(3)))*(cos(X(4))*sin(X(6)) - cos(X(6))*sin(X(4))*sin(X(5)))), dt*(cos(X(4))*cos(X(5))*cos(X(6))*(X(9) - dt*(X(15) - u(3))) - cos(X(6))*sin(X(5))*(X(7) - dt*(X(13) - u(1))) + cos(X(5))*cos(X(6))*sin(X(4))*(X(8) - dt*(X(14) - u(2)))), -dt*((X(8) - dt*(X(14) - u(2)))*(cos(X(4))*cos(X(6)) + sin(X(4))*sin(X(5))*sin(X(6))) - (X(9) - dt*(X(15) - u(3)))*(cos(X(6))*sin(X(4)) - cos(X(4))*sin(X(5))*sin(X(6))) + cos(X(5))*sin(X(6))*(X(7) - dt*(X(13) - u(1)))), dt*cos(X(5))*cos(X(6)), -dt*(cos(X(4))*sin(X(6)) - cos(X(6))*sin(X(4))*sin(X(5))),  dt*(sin(X(4))*sin(X(6)) + cos(X(4))*cos(X(6))*sin(X(5))),   0,   0,   0, -dt^2*cos(X(5))*cos(X(6)),  dt^2*(cos(X(4))*sin(X(6)) - cos(X(6))*sin(X(4))*sin(X(5))), -dt^2*(sin(X(4))*sin(X(6)) + cos(X(4))*cos(X(6))*sin(X(5)));
    0, 1, 0, -dt*((X(8) - dt*(X(14) - u(2)))*(cos(X(6))*sin(X(4)) - cos(X(4))*sin(X(5))*sin(X(6))) + (X(9) - dt*(X(15) - u(3)))*(cos(X(4))*cos(X(6)) + sin(X(4))*sin(X(5))*sin(X(6)))), dt*(cos(X(4))*cos(X(5))*sin(X(6))*(X(9) - dt*(X(15) - u(3))) - sin(X(5))*sin(X(6))*(X(7) - dt*(X(13) - u(1))) + cos(X(5))*sin(X(4))*sin(X(6))*(X(8) - dt*(X(14) - u(2)))),  dt*((X(9) - dt*(X(15) - u(3)))*(sin(X(4))*sin(X(6)) + cos(X(4))*cos(X(6))*sin(X(5))) - (X(8) - dt*(X(14) - u(2)))*(cos(X(4))*sin(X(6)) - cos(X(6))*sin(X(4))*sin(X(5))) + cos(X(5))*cos(X(6))*(X(7) - dt*(X(13) - u(1)))), dt*cos(X(5))*sin(X(6)),  dt*(cos(X(4))*cos(X(6)) + sin(X(4))*sin(X(5))*sin(X(6))), -dt*(cos(X(6))*sin(X(4)) - cos(X(4))*sin(X(5))*sin(X(6))),   0,   0,   0, -dt^2*cos(X(5))*sin(X(6)), -dt^2*(cos(X(4))*cos(X(6)) + sin(X(4))*sin(X(5))*sin(X(6))),  dt^2*(cos(X(6))*sin(X(4)) - cos(X(4))*sin(X(5))*sin(X(6)));
    0, 0, 1,                                                          dt*(cos(X(4))*cos(X(5))*(X(8) - dt*(X(14) - u(2))) - cos(X(5))*sin(X(4))*(X(9) - dt*(X(15) - u(3)))),                        -dt*(cos(X(5))*(X(7) - dt*(X(13) - u(1))) + cos(X(4))*sin(X(5))*(X(9) - dt*(X(15) - u(3))) + sin(X(4))*sin(X(5))*(X(8) - dt*(X(14) - u(2)))),                                                                                                                                                                                0,        -dt*sin(X(5)),                              dt*cos(X(5))*sin(X(4)),                              dt*cos(X(4))*cos(X(5)),   0,   0,   0,          dt^2*sin(X(5)),                             -dt^2*cos(X(5))*sin(X(4)),                             -dt^2*cos(X(4))*cos(X(5));
    0, 0, 0,                                                                                                                                         1,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0, -dt,   0,   0,                     0,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       1,                                                                                                                                                                                0,                  0,                                               0,                                               0,   0, -dt,   0,                     0,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                1,                  0,                                               0,                                               0,   0,   0, -dt,                     0,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  1,                                               0,                                               0,   0,   0,   0,                   -dt,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               1,                                               0,   0,   0,   0,                     0,                                               -dt,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               1,   0,   0,   0,                     0,                                                 0,                                               -dt;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0,   1,   0,   0,                     0,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0,   0,   1,   0,                     0,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0,   0,   0,   1,                     0,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0,   0,   0,   0,                     1,                                                 0,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0,   0,   0,   0,                     0,                                                 1,                                                 0;
    0, 0, 0,                                                                                                                                         0,                                                                                                                                       0,                                                                                                                                                                                0,                  0,                                               0,                                               0,   0,   0,   0,                     0,                                                 0,                                                 1];
end

function jacob = Jf_u(X,dt)
jacob = [ dt^2*cos(X(5))*cos(X(6)), -dt^2*(cos(X(4))*sin(X(6)) - cos(X(6))*sin(X(4))*sin(X(5))),  dt^2*(sin(X(4))*sin(X(6)) + cos(X(4))*cos(X(6))*sin(X(5))),  0,  0,  0;
    dt^2*cos(X(5))*sin(X(6)),  dt^2*(cos(X(4))*cos(X(6)) + sin(X(4))*sin(X(5))*sin(X(6))), -dt^2*(cos(X(6))*sin(X(4)) - cos(X(4))*sin(X(5))*sin(X(6))),  0,  0,  0;
    -dt^2*sin(X(5)),                              dt^2*cos(X(5))*sin(X(4)),                              dt^2*cos(X(4))*cos(X(5)),  0,  0,  0;
    0,                                                 0,                                                 0, dt,  0,  0;
    0,                                                 0,                                                 0,  0, dt,  0;
    0,                                                 0,                                                 0,  0,  0, dt;
    dt,                                                 0,                                                 0,  0,  0,  0;
    0,                                                dt,                                                 0,  0,  0,  0;
    0,                                                 0,                                                dt,  0,  0,  0;
    0,                                                 0,                                                 0,  0,  0,  0;
    0,                                                 0,                                                 0,  0,  0,  0;
    0,                                                 0,                                                 0,  0,  0,  0;
    0,                                                 0,                                                 0,  0,  0,  0;
    0,                                                 0,                                                 0,  0,  0,  0;
    0,                                                 0,                                                 0,  0,  0,  0];
end
